#include "chatter.h"



// https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes


// First v-key (0x00) starts on line 10
LPWSTR WinVirtualKeyCodes[] = {
    L"Undefined (0x00)",
    L"VK_LBUTTON",
    L"VK_RBUTTON",
    L"VK_CANCEL",
    L"VK_MBUTTON",
    L"VK_XBUTTON1",
    L"VK_XBUTTON2",
    L"Undefined (0x07)",
    L"VK_BACK",
    L"VK_TAB",
    L"Reserved (0x0A)",
    L"Reserved (0x0B)",
    L"VK_CLEAR",
    L"VK_RETURN",
    L"Undefined (0x0E)",
    L"Undefined (0x0F)",
    L"VK_SHIFT",
    L"VK_CONTROL",
    L"VK_MENU",
    L"VK_PAUSE",
    L"VK_CAPITAL",
    L"VK_KANA/VK_HANGUEL/VK_HANGUL",
    L"VK_IME_ON",
    L"VK_JUNJA",
    L"VK_FINAL",
    L"VK_HANJA/VK_KANJI",
    L"VK_IME_OFF",
    L"VK_ESCAPE",
    L"VK_CONVERT",
    L"VK_NONCONVERT",
    L"VK_ACCEPT",
    L"VK_MODECHANGE",
    L"VK_SPACE",
    L"VK_PRIOR",
    L"VK_NEXT",
    L"VK_END",
    L"VK_HOME",
    L"VK_LEFT",
    L"VK_UP",
    L"VK_RIGHT",
    L"VK_DOWN",
    L"VK_SELECT",
    L"VK_PRINT",
    L"VK_EXECUTE",
    L"VK_SNAPSHOT",
    L"VK_INSERT",
    L"VK_DELETE",
    L"VK_HELP",
    L"0 key",
    L"1 key",
    L"2 key",
    L"3 key",
    L"4 key",
    L"5 key",
    L"6 key",
    L"7 key",
    L"8 key",
    L"9 key",
    L"Undefined (0x3A)",
    L"Undefined (0x3B)",
    L"Undefined (0x3C)",
    L"Undefined (0x3D)",
    L"Undefined (0x3E)",
    L"Undefined (0x3F)",
    L"Undefined (0x40)",
    L"A key",
    L"B key",
    L"C key",
    L"D key",
    L"E key",
    L"F key",
    L"G key",
    L"H key",
    L"I key",
    L"J key",
    L"K key",
    L"L key",
    L"M key",
    L"N key",
    L"O key",
    L"P key",
    L"Q key",
    L"R key",
    L"S key",
    L"T key",
    L"U key",
    L"V key",
    L"W key",
    L"X key",
    L"Y key",
    L"Z key",
    L"VK_LWIN",
    L"VK_RWIN",
    L"VK_APPS",
    L"Reserved (0x5E)",
    L"VK_SLEEP",
    L"VK_NUMPAD0",
    L"VK_NUMPAD1",
    L"VK_NUMPAD2",
    L"VK_NUMPAD3",
    L"VK_NUMPAD4",
    L"VK_NUMPAD5",
    L"VK_NUMPAD6",
    L"VK_NUMPAD7",
    L"VK_NUMPAD8",
    L"VK_NUMPAD9",
    L"VK_MULTIPLY",
    L"VK_ADD",
    L"VK_SEPARATOR",
    L"VK_SUBTRACT",
    L"VK_DECIMAL",
    L"VK_DIVIDE",
    L"VK_F1",
    L"VK_F2",
    L"VK_F3",
    L"VK_F4",
    L"VK_F5",
    L"VK_F6",
    L"VK_F7",
    L"VK_F8",
    L"VK_F9",
    L"VK_F10",
    L"VK_F11",
    L"VK_F12",
    L"VK_F13",
    L"VK_F14",
    L"VK_F15",
    L"VK_F16",
    L"VK_F17",
    L"VK_F18",
    L"VK_F19",
    L"VK_F20",
    L"VK_F21",
    L"VK_F22",
    L"VK_F23",
    L"VK_F24",
    L"Unassigned (0x88)",
    L"Unassigned (0x89)",
    L"Unassigned (0x8A)",
    L"Unassigned (0x8B)",
    L"Unassigned (0x8C)",
    L"Unassigned (0x8D)",
    L"Unassigned (0x8E)",
    L"Unassigned (0x8F)",
    L"VK_NUMLOCK",
    L"VK_SCROLL",
    L"OEM specific (0x92)",
    L"OEM specific (0x93)",
    L"OEM specific (0x94)",
    L"OEM specific (0x95)",
    L"OEM specific (0x96)",
    L"Unassigned (0x97)",
    L"Unassigned (0x98)",
    L"Unassigned (0x99)",
    L"Unassigned (0x9A)",
    L"Unassigned (0x9B)",
    L"Unassigned (0x9C)",
    L"Unassigned (0x9D)",
    L"Unassigned (0x9E)",
    L"Unassigned (0x9F)",
    L"VK_LSHIFT",
    L"VK_RSHIFT",
    L"VK_LCONTROL",
    L"VK_RCONTROL",
    L"VK_LMENU",
    L"VK_RMENU",
    L"VK_BROWSER_BACK",
    L"VK_BROWSER_FORWARD",
    L"VK_BROWSER_REFRESH",
    L"VK_BROWSER_STOP",
    L"VK_BROWSER_SEARCH",
    L"VK_BROWSER_FAVORITES",
    L"VK_BROWSER_HOME",
    L"VK_VOLUME_MUTE",
    L"VK_VOLUME_DOWN",
    L"VK_VOLUME_UP",
    L"VK_MEDIA_NEXT_TRACK",
    L"VK_MEDIA_PREV_TRACK",
    L"VK_MEDIA_STOP",
    L"VK_MEDIA_PLAY_PAUSE",
    L"VK_LAUNCH_MAIL",
    L"VK_LAUNCH_MEDIA_SELECT",
    L"VK_LAUNCH_APP1",
    L"VK_LAUNCH_APP2",
    L"Reserved (0xB8)",
    L"Reserved (0xB9)",
    L"VK_OEM_1",
    L"VK_OEM_PLUS",
    L"VK_OEM_COMMA",
    L"VK_OEM_MINUS",
    L"VK_OEM_PERIOD",
    L"VK_OEM_2",
    L"VK_OEM_3",
    L"Reserved (0xC1)",
    L"Reserved (0xC2)",
    L"Reserved (0xC3)",
    L"Reserved (0xC4)",
    L"Reserved (0xC5)",
    L"Reserved (0xC6)",
    L"Reserved (0xC7)",
    L"Reserved (0xC8)",
    L"Reserved (0xC9)",
    L"Reserved (0xCA)",
    L"Reserved (0xCB)",
    L"Reserved (0xCC)",
    L"Reserved (0xCD)",
    L"Reserved (0xCE)",
    L"Reserved (0xCF)",
    L"Reserved (0xD0)",
    L"Reserved (0xD1)",
    L"Reserved (0xD2)",
    L"Reserved (0xD3)",
    L"Reserved (0xD4)",
    L"Reserved (0xD5)",
    L"Reserved (0xD6)",
    L"Reserved (0xD7)",
    L"Unassigned (0xD8)",
    L"Unassigned (0xD9)",
    L"Unassigned (0xDA)",
    L"VK_OEM_4",
    L"VK_OEM_5",
    L"VK_OEM_6",
    L"VK_OEM_7",
    L"VK_OEM_8",
    L"Reserved (0xE0)",
    L"OEM specific (0xE1)",
    L"VK_OEM_102",
    L"OEM specific (0xE3)",
    L"OEM specific (0xE4)",
    L"VK_PROCESSKEY",
    L"OEM specific (0xE6)",
    L"VK_PACKET",
    L"Unassigned (0xE8)",
    L"OEM specific(0xE9)",
    L"OEM specific(0xEA)",
    L"OEM specific(0xEB)",
    L"OEM specific(0xEC)",
    L"OEM specific(0xED)",
    L"OEM specific(0xEE)",
    L"OEM specific(0xEF)",
    L"OEM specific(0xF0)",
    L"OEM specific(0xF1)",
    L"OEM specific(0xF2)",
    L"OEM specific(0xF3)",
    L"OEM specific(0xF4)",
    L"OEM specific(0xF5)",
    L"VK_ATTN",
    L"VK_CRSEL",
    L"VK_EXSEL",
    L"VK_EREOF",
    L"VK_PLAY",
    L"VK_ZOOM",
    L"VK_NONAME",
    L"VK_PA1",
    L"VK_OEM_CLEAR",
    L"Undefined (0xFF)"
};

C_ASSERT(ARRAYSIZE(WinVirtualKeyCodes) == 0x100);

LPWSTR
GetVKeyText(
    _In_ USHORT VKey
    )
{
    return WinVirtualKeyCodes[VKey];
}